<a href="https://colab.research.google.com/github/VishalSingh1703/Placement_Training/blob/main/DAY4_Backtracking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Generate Parenthesis

In [14]:
def permute(open, close, s, ans):
  if open == 0 and close == 0: ans.append(s)
  if open > 0:  permute(open-1, close, s + '(', ans)
  if close > 0 and close > open: permute(open, close - 1, s + ')', ans)


def generate(n):
  ans = []
  s = ""
  permute(n, n, s, ans)
  return ans

n = int(input("Enter a number: "))
ans = generate(n)
print("The generated parenthesis are: " + str(ans))

Enter a number: 3
The generated parenthesis are: ['((()))', '(()())', '(())()', '()(())', '()()()']


Permutations of a String

In [22]:
# def swap(s, a, b):
#   temp = s[a]
#   s[a] = s[b]
#   s[b] = temp

def permute(idx, s, ans):
  if (idx == len(s)):
    ans.append(''.join(s))
    return
  for i in range(idx, len(s)):
    # swap(s, i, idx)
    s[i], s[idx] = s[idx], s[i]
    permute(idx + 1, s, ans)
    s[i], s[idx] = s[idx], s[i]
    # swap(s, i, idx)

s = input("Enter a string: ")
ans = []
permute(0, list(s), ans)
print(ans)

Enter a string: ABC
['ABC', 'ACB', 'BAC', 'BCA', 'CBA', 'CAB']


Spiral Matrix

In [36]:
import numpy as np

def spiral(mat):
  l, r = 0, len(mat[0])
  t, b= 0, len(mat)
  ans = []
  while(l<r and t<b):
    for x in range(l, r):
      ans.append(mat[t][x])
    t += 1

    for y in range(t, b):
      ans.append(mat[y][r - 1])
    r -= 1

    if(t >= b or l >= b): break

    if t<b:
      for x in range(r - 1, l - 1, -1):
        ans.append(mat[b - 1][x])
      b -= 1

    if l<r:
      for y in range(b - 1, t - 1, -1):
        ans.append(mat[y][l])
      l += 1

  return ans

# n = int(input("Enter the dimension of the matrix: "))
# mat = []

# for i in range(n):
#     row = []
#     for j in range(n):
#         element = int(input(f"Enter the element at position ({i + 1}, {j + 1}): "))
#         row.append(element)
#     mat.append(row)

mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

for row in mat:
    print(row)

ans = spiral(mat)
print(ans)


[1 2 3]
[4 5 6]
[7 8 9]
[1, 2, 3, 6, 9, 8, 7, 4, 5]


In [6]:
class Solution:
  def __init__(self):
    self.delRow = [1, -1, 0, 0]
    self.delCol = [0, 0, -1, 1]

  def numIsands(self, grid):
    island = 0
    n = len(grid)
    m = len(grid[0])
    vis = [[0] * m for _ in range(n)]

    for i in range(n):
      for j in range(m):
        if grid[i][j] == 1 and vis[i][j] == 0:
          island += 1
          self.dfs(grid, vis, n, m, i, j)
    return island

  def dfs(self, grid, vis, n, m, row, col):
    if row < 0 or row >= n or col < 0 or col >= m or vis[row][col] == 1:
      return

    vis[row][col] = 1

    for i in range(4):
      nRow = row + self.delRow[i]
      nCol = col + self.delCol[i]

      if 0 <= nRow < n and 0 <= nCol < m and grid[nRow][nCol] == 1 and vis[nRow][nCol] == 0:
        self.dfs(grid, vis, n, m, nRow, nCol)


sol = Solution()
grid = [
    [1, 1, 1, 1, 0],
    [1, 1, 0, 1, 0],
    [1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1]
]
res = sol.numIsands(grid)
print(res)

2
